# Generated by Django 4.2 on 2023-05-30 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='location',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='university',
        ),
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 30, 11, 23, 22, 911671, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='customuser',
            name='motto',
            field=models.CharField(default='안녕', max_length=500),
        ),
    ]
