# Generated by Django 4.2 on 2023-05-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="posting",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="../media/images/"
            ),
        ),
    ]
