# Generated by Django 4.2 on 2023-05-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini", "0003_alter_posting_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posting",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
