# Generated by Django 4.2 on 2023-05-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini", "0004_alter_posting_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="posting",
            name="category",
            field=models.CharField(
                default="", max_length=10, null=True, verbose_name="week"
            ),
        ),
    ]
