# Generated by Django 4.2 on 2023-05-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini", "0005_posting_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posting",
            name="category",
            field=models.CharField(
                choices=[
                    ("월요일", "월요일"),
                    ("화요일", "화요일"),
                    ("수요일", "수요일"),
                    ("목요일", "목요일"),
                    ("금요일", "금요일"),
                    ("토요일", "토요일"),
                    ("일요일", "일요일"),
                ],
                max_length=10,
                verbose_name="week",
            ),
        ),
    ]
