# Generated by Django 4.2 on 2023-05-16 09:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mini", "0006_alter_posting_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posting",
            name="category",
            field=models.CharField(
                default="", max_length=10, null=True, verbose_name="week"
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20)),
                ("comment_text", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="mini.posting",
                    ),
                ),
            ],
        ),
    ]
