# Generated by Django 4.2 on 2023-05-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='image',
            field=models.ImageField(null=True, upload_to='posts/image'),
        ),
        migrations.AddField(
            model_name='main',
            name='updatedate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='uploaddate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
