# Generated by Django 4.2 on 2023-05-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0003_alter_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='image',
        ),
        migrations.RemoveField(
            model_name='main',
            name='updatedate',
        ),
        migrations.AlterField(
            model_name='main',
            name='uploaddate',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
