# Generated by Django 4.2 on 2023-05-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0006_hashtag_main_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='main_photo'),
        ),
    ]
