# Generated by Django 4.2 on 2023-05-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('body', models.TextField()),
                ('re', models.CharField(max_length=300)),
            ],
        ),
    ]
