# Generated by Django 4.2 on 2023-05-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(default='여성', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='travelcities',
            field=models.CharField(default='서울', max_length=100),
        ),
    ]
