# Generated by Django 4.2 on 2023-05-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddabong', '0003_hashtag_ddabong_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddabong',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='ddabong_photo'),
        ),
    ]
